### PR TITLE
Docs(init): Done bug template

### PR DESCRIPTION
**Pull request by Alvsanflo**
Implemented bug template for issues

### CODE REVIEW

**Review by jaicabher1 — APPROVED** [review]
Perfect!

**Review by CarlosNuchera — APPROVED** [review]

**Review by gonsanmar2 — APPROVED** [review]
ok

**Review by ferbarbar1 — APPROVED** [review]
Everything OK

**Review by marrocrod — APPROVED** [review]
Everything OK

**Pull request merged**
